const jwt = require("jsonwebtoken");
const nodemailer = require("nodemailer");
const axios = require("axios");
// const crypto = require("crypto");
//otp generate
module.exports.otpGenerate = () => {
  const otp = Math.floor(1000 + Math.random() * 9000).toString();
  return otp;
};
//generate token
module.exports.generateToken = (user) => {
  const authorization = jwt.sign({ user: user }, process.env.SECKEY);
  return authorization;
};

//send otp on Mail
module.exports.sendOtpOnMail = (email, otp) => {
  console.log(process.env.EMAIL_USER);
  try {
    let transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });
    transporter.sendMail({
      from: process.env.EMAIL_FROM,
      to: email,
      subject: "Your OTP",
      text: `Your OTP is: ${otp}`,
      html: `<div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
  <div style="margin:50px auto;width:70%;padding:20px 0">
    <div class="brand" style="border-bottom:1px solid #eee;background: #1d4a35 !important;color: white;padding: 10px 0 10px 10px;border-radius: 2px;">
      <a href="" style="font-size:1.4em;color: #fff;text-decoration:none;font-weight:600">45X</a>
    </div>
    <p style="font-size:1.1em">Hi,</p>
    <p>Thank you for choosing 45X. Use the following OTP to complete your Sign Up procedures. OTP is valid for 3 minutes</p>
    <h2 style="background: #1d4a35;margin: 0 auto;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">${otp}</h2>
    <p style="font-size:0.9em;">Regards,<br />Team 45X</p>
    <hr style="border:none;border-top:1px solid #eee" />
    
  </div>
</div>`,
    });
  } catch (error) {
    console.log(error);
  }
};

// send otp on Number
module.exports.sendOtpOnNumber = async (phone, otp) => {
  const apiKey = process.env.API_KEY_2FACTOR;
  const url = `https://2factor.in/API/V1/${apiKey}/SMS/${phone}/${otp}`;
  try {
    const response = await axios.get(url);
    console.log(response.data);
    if (response.data.Status === "Success") {
      console.log(`OTP sent successfully to ${phone}`);
    } else {
      console.error(`Failed to send OTP to ${phone}: ${response.data.Details}`);
    }
  } catch (error) {
    console.error(`Error sending OTP to ${phone}:`, error);
  }
};

// module.exports.generateRandomPassword = () => {
//   return crypto.randomBytes(8).toString("hex"); // Generates a random 16 character hex string
// };

module.exports.generateUsername = async () => {
  const oneWordAdjectives = [
    "Happy",
    "Angry",
    "Bright",
    "Dark",
    "Calm",
    "Brave",
    "Quick",
    "Slow",
    "Smart",
    "Strong",
    "Large",
    "Small",
    "Hot",
    "Cold",
    "Loud",
    "Quiet",
    "Bold",
    "Shy",
    "Gentle",
    "Fierce",
    "Kind",
    "Cruel",
    "Rich",
    "Young",
    "Fast",
    "Slow",
    "Friendly",
    "Tall",
    "Short",
    "Heavy",
    "Light",
    "Clean",
    "Soft",
    "Hard",
    "Fresh",
    "Stale",
    "Sweet",
    "Bitter",
    "Sharp",
    "Dull",
    "Warm",
    "Cool",
    "Silly",
    "Serious",
    "Beautiful",
    "Lazy",
    "Active",
    "Creative",
    "Funny",
    "Boring",
    "Polite",
    "Timid",
    "Smooth",
    "Rough",
    "Loyal",
    "Treacherous",
    "Brilliant",
    "Joyful",
    "Miserable",
    "Healthy",
    "Lively",
    "Vivid",
    "Faded",
    "Precise",
    "Vague",
    "Proud",
    "Honest",
    "Dishonest",
    "Clever",
    "Foolish",
    "Grumpy",
    "Cheerful",
    "Impatient",
    "Tense",
    "Friendly",
    "Hostile",
    "Optimistic",
    "Pessimistic",
    "Flexible",
    "Stubborn",
    "Caring",
    "Selfish",
    "Generous",
    "Greedy",
    "Confident",
    "Insecure",
    "Curious",
    "Apathetic",
    "Determined",
    "Indecisive",
    "Energetic",
    "Enthusiastic",
    "Reluctant",
    "Faithful",
    "Logical",
    "Practical",
    "Dreamy",
    "Reliable",
    "Unreliable",
    "Organized",
    "Messy",
  ];
  const oneWordColorNames = [
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
    "Pink",
    "Brown",
    "Black",
    "White",
    "Gray",
    "Cyan",
    "Magenta",
    "Maroon",
    "Olive",
    "Lime",
    "Teal",
    "Navy",
    "Coral",
    "Turquoise",
    "Lavender",
    "Beige",
    "Ivory",
    "Gold",
    "Silver",
    "Bronze",
    "Crimson",
    "Fuchsia",
    "Indigo",
    "Violet",
    "Salmon",
    "Peach",
    "Azure",
    "Aqua",
    "Amber",
    "Emerald",
    "Ruby",
    "Sapphire",
    "Rose",
    "Mustard",
    "Chocolate",
    "Charcoal",
    "Cobalt",
    "Copper",
    "Slate",
    "Blush",
    "Orchid",
    "Tangerine",
    "Lilac",
    "Periwinkle",
    "Cerulean",
    "Mauve",
    "Plum",
    "Sand",
    "Taupe",
    "Rust",
    "Burgundy",
    "Ochre",
    "Chartreuse",
    "Amethyst",
    "Jade",
    "Topaz",
    "Saffron",
    "Mint",
    "Sky",
    "Royal",
    "Forest",
    "Lemon",
    "Scarlet",
    "Firebrick",
    "Tomato",
    "Hotpink",
    "Khaki",
    "Cornflower",
    "Thistle",
    "Snow",
    "Honeydew",
    "Lavender",
    "Wheat",
    "Gold",
    "Seashell",
    "Linen",
    "Bisque",
    "Antique",
    "Dimgray",
    "Slategray",
    "Darkslate",
    "Black",
    "Coral",
    "Tan",
  ];
  const emotionNames = [
    "Happiness",
    "Sadness",
    "Anger",
    "Fear",
    "Surprise",
    "Disgust",
    "Love",
    "Joy",
    "Excitement",
    "Nervousness",
    "Anxiety",
    "Contentment",
    "Frustration",
    "Embarrassment",
    "Guilt",
    "Shame",
    "Pride",
    "Jealousy",
    "Envy",
    "Relief",
    "Gratitude",
    "Awe",
    "Compassion",
    "Empathy",
    "Loneliness",
    "Boredom",
    "Curiosity",
    "Confusion",
    "Disappointment",
    "Determination",
    "Hope",
    "Fearlessness",
    "Regret",
    "Resentment",
    "Satisfaction",
    "Inspiration",
    "Admiration",
    "Disapproval",
    "Contempt",
    "Trust",
    "Bitterness",
    "Despair",
    "Remorse",
    "Terror",
    "Annoyance",
    "Anticipation",
    "Indifference",
    "Longing",
    "Apprehension",
    "Shock",
    "Vulnerability",
    "Euphoria",
    "Sympathy",
    "Melancholy",
    "Optimism",
    "Pessimism",
    "Hostility",
    "Resignation",
    "Triumph",
    "Affection",
    "Passion",
    "Infatuation",
    "Resilience",
    "Serenity",
    "Courage",
    "Surrealism",
    "Amusement",
    "Reluctance",
    "Exhilaration",
    "Astonishment",
    "Hysteria",
    "Isolation",
    "Rejection",
    "Elation",
    "Desperation",
    "Homesickness",
    "Disillusionment",
    "Nostalgia",
    "Suspicion",
    "Agitation",
    "Skepticism",
    "Hopelessness",
    "Betrayal",
    "Vindication",
    "Adoration",
    "Fascination",
    "Reverence",
    "Mortification",
    "Amazement",
    "Relief",
    "Suspense",
    "Skepticism",
    "Disdain",
    "Tension",
    "Surprise",
    "Reluctance",
    "Bliss",
    "Despondency",
    "Exasperation",
    "Zeal",
    "Vindication",
    "Remorse",
    "Worry",
    "Reluctance",
    "Grief",
    "Solitude",
    "Bewilderment",
    "Devotion",
    "Glory",
    "Content",
    "Reluctance",
    "Jubilation",
    "Calmness",
    "Astonishment",
    "Fury",
    "Insecurity",
    "Grudge",
    "Irritation",
    "Regret",
    "Forlornness",
  ];
  const animalNames = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Donkey",
    "Baboon",
    "Badger",
    "Barracuda",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bison",
    "Boar",
    "Buffalo",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caribou",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Chamois",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Clam",
    "Cobra",
    "Cockroach",
    "Cod",
    "Cormorant",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Curlew",
    "Deer",
    "Dinosaur",
    "Dog",
    "Dogfish",
    "Dolphin",
    "Dotterel",
    "Dove",
    "Dragonfly",
    "Duck",
    "Dugong",
    "Dunlin",
    "Eagle",
    "Echidna",
    "Eel",
    "Eland",
    "Elephant",
    "Elephant Seal",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Fish",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gaur",
    "Gazelle",
    "Gerbil",
    "Giant Panda",
    "Giraffe",
    "Gnat",
    "Gnu",
    "Goat",
    "Goldfinch",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Goshawk",
    "Grasshopper",
    "Grouse",
    "Guanaco",
    "Guinea Fowl",
    "Guinea Pig",
    "Gull",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Human",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Ibis",
    "Jackal",
    "Jaguar",
    "Jay",
    "Jellyfish",
    "Kangaroo",
    "Kingfisher",
    "Koala",
    "Komodo Dragon",
    "Kookaburra",
    "Kouprey",
    "Kudu",
    "Lapwing",
    "Lark",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Locust",
    "Loris",
    "Louse",
    "Lyrebird",
    "Magpie",
    "Mallard",
    "Manatee",
    "Mandrill",
    "Mantis",
    "Marten",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Mouse",
    "Mule",
    "Narwhal",
    "Newt",
    "Nightingale",
    "Octopus",
    "Okapi",
    "Opossum",
    "Oryx",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Oyster",
    "Panther",
    "Parrot",
    "Partridge",
    "Peafowl",
    "Pelican",
    "Penguin",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Quail",
    "Quelea",
    "Quetzal",
    "Rabbit",
    "Raccoon",
    "Rail",
    "Ram",
    "Rat",
    "Raven",
    "Red Deer",
    "Red Panda",
    "Reindeer",
    "Rhinoceros",
    "Rook",
    "Salamander",
    "Salmon",
    "Sand Dollar",
    "Sandpiper",
    "Sardine",
    "Scorpion",
    "Sea Lion",
    "Sea Urchin",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Skunk",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Squid",
    "Squirrel",
    "Starling",
    "Stingray",
    "Stinkbug",
    "Stork",
    "Swallow",
    "Swan",
    "Tapir",
    "Tarsier",
    "Termite",
    "Tiger",
    "Toad",
    "Trout",
    "Turkey",
    "Turtle",
    "Viper",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wildcat",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodcock",
    "Woodpecker",
    "Worm",
    "Wren",
    "Yak",
    "Zebra",
  ];
  const allFirstWords = [...oneWordAdjectives, ...oneWordColorNames];
  const randomFirstWord =
    allFirstWords[Math.floor(Math.random() * allFirstWords.length)];
  const randomAnimal =
    animalNames[Math.floor(Math.random() * animalNames.length)];

  return `${randomFirstWord}_${randomAnimal}`;
};

module.exports.getImageForUsername = async () => {
  const res = await axios(
    "https://api.unsplash.com/photos/random/?page=1&client_id=Lguhjmp-bZILQ0nlJA3ziQGvwEQzm4l1znHy2dKPXas&query=animal"
  );
  console.log(res.data.links.download);
  return res.data.links.download;
};
